### ISSUE TITLE
back button doesn't work

### ISSUE THREAD

**Issue by irfansharif** [seveneightn9ne/dino-budgeter#22]
Hey, cool project! Ran into this issue where the back button didn't work as expected. Here's what I did:

1. Clicked on "Rent"
<img width="696" alt="image" src="https://user-images.githubusercontent.com/10536690/65654822-163cc980-dfe8-11e9-8902-88cd627cb03e.png">

2. Working as expected so far, hit "back" on my browser
<img width="588" alt="image" src="https://user-images.githubusercontent.com/10536690/65654834-1e950480-dfe8-11e9-8d06-d99f55451a5f.png">

3. Welp
<img width="558" alt="image" src="https://user-images.githubusercontent.com/10536690/65654892-44220e00-dfe8-11e9-86e0-67eceab4a4e0.png">

**Comment by seveneightn9ne** [comment]
Thanks for the report! Looks like this is due to navigating with React Router's `<Redirect>` component, which we can fix by using the `push={true}` option.
