### ISSUE TITLE
"save" button not working on new txn

### ISSUE THREAD

**Issue by irfansharif** [seveneightn9ne/dino-budgeter#23]
I tried running a local server off of 847af41, but ran into this issue where hitting "save" didn't work.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/10536690/65656119-af6ddf00-dfec-11e9-8df7-c12ac8d989af.png">

Console log shows the following:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/10536690/65656151-d0363480-dfec-11e9-838c-0e0b32417e74.png">

(This seems to work fine on the revision currently hosted on dino.jesskenney.com.)

**Comment by seveneightn9ne** [comment]
Hi, can you post the server side logs and also check the browser's network devtool to see if the request failed? The warning the console shows should be ignorable.

**Comment by seveneightn9ne** [comment]
Yeah, confirming I can reproduce. There's no network request made / no server log generated
